gmt/views/general.py
import datetime
import random
import re

from bson import ObjectId
from email_validator import validate_email, EmailNotValidError
from flask import Blueprint, render_template, redirect, request, url_for, current_app
from flask_mail import Message
from werkzeug import Response
from markdown import markdown
from flask_login import login_required, current_user

from ..news import get_news
from .. import mongo, login_manager, User, mail
from ..utils import random_language_greeting
from ..extras import get_daily_coding_challenge, get_trending_repos, get_surprise

bp = Blueprint("general", __name__)


@bp.route("/", methods=["GET", "POST"])
def index():
    """Render the home page."""
    if request.method == "POST":
        email = request.form.get("email")
        if email:
            return redirect(url_for("auth.subscribe", email=email))

    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )

    posts = mongo.db.articles.find(
        {"date": {"$gte": datetime.datetime.utcnow() - datetime.timedelta(hours=25)}}
    )

    # Mix the posts
    posts = list(posts)
    if len(posts) > 2:
        # Gets a random post and removes it from the list
        post1 = random.choice(posts)
        posts.remove(post1)
        # Gets a second random post
        post2 = random.choice(posts)

        # set limits for the description to 360 characters and add more length for each [link] tag
        limit1 = 360 + post1["description"][:360].count("[link]") * 30
        limit2 = 360 + post2["description"][:360].count("[link]") * 30

        # slice the description to the limit
        post1["description"] = post1["description"][:limit1]
        post2["description"] = post2["description"][:limit2]

        # remove unterminated [link] tags
        if re.search("\[link\]\([^\)]*[^\)]$", post1["description"]):
            post1["description"] = re.sub(
                "\[link\]\(.*[^\)]$", "", post1["description"]
            )
        if re.search("\[link\]\([^\)]*[^\)]$", post2["description"]):
            post2["description"] = re.sub(
                "\[link\]\([^\)]*[^\)]$", "", post2["description"]
            )

        # add ellipses and markdown it
        post1["description"] = markdown(post1["description"] + "...")
        post2["description"] = markdown(post2["description"] + "...")
        posts = [post1, post2]
    else:
        posts = []

    return render_template("general/index.html", news=posts)


@bp.route("/news")
def news():
    """Render the newspaper."""
    posts = list(
        mongo.db.articles.find(
            {
                "date": {
                    "$gte": datetime.datetime.utcnow() - datetime.timedelta(hours=25)
                }
            }
        )
    )

    if not posts:
        posts = get_news(choice="BBC")

    random.shuffle(posts)

    return render_template(
        "general/news.html",
        posts=posts[:12],
        theme="light",
        markdown=markdown,
        domain_name=current_app.config["DOMAIN_NAME"],
        repos=get_trending_repos(),
        coding_challenge=get_daily_coding_challenge(),
        surprise=get_surprise(),
        random_language_greeting=random_language_greeting(),
    )


@bp.route("/about")
def about():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    return render_template("general/about.html", no_meta=True)


@bp.route("/contact", methods=["GET", "POST"])
def contact():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    if request.method == "POST":
        fake_email = request.form.get("email")
        if fake_email:
            return render_template(
                "general/contact.html",
                error="Invalid email address",
                success=False,
                no_meta=True,
            )
        email = request.form.get("real_email")
        name = request.form.get("name")
        subject = request.form.get("subject")
        message = request.form.get("message")
        try:
            validate_email(email)
        except EmailNotValidError as e:
            return render_template(
                "general/contact.html",
                error="Invalid email address",
                success=False,
                no_meta=True,
            )
        else:
            msg = Message(
                subject=f"Contact Form Submission from {name} - {subject}",
                sender=("Good Morning Tech", current_app.config["MAIL_USERNAME"]),
                recipients=["support@goodmorningtech.news"],
                body=f"From: {name} <{email}>,\n{message}",
            )
            mail.send(msg)
            return render_template(
                "general/contact.html", success=True, error=None, no_meta=True
            )
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    return render_template(
        "general/contact.html", success=False, error=None, no_meta=True
    )


@bp.route("/contribute")
def contribute():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    return render_template("general/contribute.html")


@bp.route("/morning")
def morning():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    return render_template("general/morning.html", no_meta=True)


@bp.route("/privacy")
def privacy():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    return render_template("general/privacy_policy.html")


@bp.route("/tos")
def terms():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    return render_template("general/tos.html")


@bp.route("/credits")
def credits():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    return render_template("general/credits.html")


@bp.route("/sitemap.xml")
def sitemap():
    """Render the sitemap.xml."""

    sitemap_xml = render_template("general/sitemap.xml")
    response = Response(sitemap_xml, mimetype="text/xml")
    response.headers["Content-Type"] = "application/xml"

    return response


@bp.route("/robots.txt")
def robots():
    """Render the robots.txt."""
    robots_txt = render_template("general/robots.txt")
    response = Response(robots_txt, mimetype="text/plain")
    response.headers["Content-Type"] = "text/plain"

    return response


@login_manager.user_loader
def load_user(user_id):
    user_doc = mongo.db.writers.find_one({"_id": ObjectId(user_id)})
    if user_doc:
        user = User()
        user.id = str(user_doc["_id"])
        return user
    else:
        return None


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for("writers.login"))

gmt/views/writers.py
import datetime
import random

import re

import pytz
import requests
from bson import ObjectId
from flask import (
    Blueprint,
    current_app,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, current_user, login_required, logout_user

from .. import mongo, User
from ..utils import clean_html, upload_file, allowed_file_types

bp = Blueprint("writers", __name__, url_prefix="/writers")


@bp.route("/")
def writers():
    return redirect(url_for("writers.portal"))


@bp.route("/apply", methods=("POST", "GET"))
def apply():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    if request.method == "POST":
        email = request.form.get("email")
        reasoning = request.form.get("reasoning")
        alt_contact = request.form.get("alt_contact")
        name = request.form.get("name")
        topics = request.form.get("topics")
        sample_link = request.form.get("sample_link")
        sample_article = request.form.get("sample_article")
        if not email or not reasoning or not name:
            return render_template(
                "writers/apply.html",
                status=f"Please fill in all fields!",
                current_user=current_user,
                no_meta=True,
            )

        user = mongo.db.users.find_one({"email": email, "confirmed": True})
        if not user:
            return render_template(
                "writers/apply.html",
                status=f"Please subscribe first,"
                f" or confirm your email by registering subscribing.",
                current_user=current_user,
                no_meta=True,
            )
        elif mongo.db.writers.find_one({"email": email, "accepted": True}):
            return render_template(
                "writers/apply.html",
                status=f"You are already a writer!",
                current_user=current_user,
                no_meta=True,
            )
        elif mongo.db.writers.find_one({"email": email, "accepted": False}):
            return render_template(
                "writers/apply.html",
                status=f"You have already applied!",
                current_user=current_user,
                no_meta=True,
            )

        writer = {
            "email": email,
            "name": name,
            "reasoning": reasoning,
            "accepted": False,
            "password": None,
            "user_name": None,  # NEEDS TO BE UNIQUE
            "confirmed": False,  # needs to confirm email when registering as writer
            "alt_contact": alt_contact,
            "topics": topics,
            "sample_link": sample_link,
            "sample_article": sample_article,
            "register_date": datetime.datetime.utcnow(),
        }
        mongo.db.writers.insert_one(writer)

        if current_app.config["WRITER_WEBHOOK"] is None:
            print("No webhook set, please set WRITER_WEBHOOK")

        # POSTS the information to a discord channel using a webhook, so we can either accept it or not
        requests.post(
            current_app.config["WRITER_WEBHOOK"],
            json={
                "content": f"""
                User with email {email} requested to join as writer. Reasoning: {reasoning}\nTopics: {topics}\nSample article link: {sample_link}\nSample article: {sample_article}\nalt contact: {alt_contact}
                """
            },
        )
        return render_template(
            "writers/apply.html",
            status=f"Thank you for applying! We will get back to you as soon as possible.",
            current_user=current_user,
            no_meta=True,
        )

    return render_template("writers/apply.html", status=None, no_meta=True)


@bp.route("/login", methods=("POST", "GET"))
def login():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        writer_db = mongo.db.writers.find_one({"email": email, "accepted": True})

        if not writer_db:
            return render_template(
                "writers/login.html",
                status=f"You are not a writer!",
                current_user=current_user,
            )
        elif not check_password_hash(writer_db["password"], password):
            return render_template("writers/login.html", status=f"Wrong password!")
        elif writer_db["confirmed"] is False:
            return render_template(
                "writers/login.html",
                status=f"Please confirm your email first!",
                current_user=current_user,
            )

        user = User()
        user.id = writer_db["_id"]

        login_user(user, remember=True)

        return redirect(url_for("writers.portal"))
    return render_template("writers/login.html", status=None)


@bp.route("/logout", methods=["POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("general.index"))


@bp.route("/register", methods=("POST", "GET"))
def register():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        password_confirm = request.form["password_confirm"]
        about = request.form.get("about")
        name = request.form.get("name")
        user_name = request.form.get("user_name")

        if len(user_name) < 3 or re.fullmatch("^[\w.-]+$", user_name) is None:
            return render_template(
                "writers/apply.html",
                status=f"User name must be at least 3 characters long and only contain"
                f" alphanumeric characters, underscores, dashes and dots.",
            )

        if password != password_confirm:
            return render_template(
                "writers/register.html", status=f"Passwords dont match!"
            )

        writer = mongo.db.writers.find_one({"email": email, "accepted": True})
        if not writer:
            return render_template(
                "writers/register.html",
                status=f"You are not a writer! Please apply first or get accepted.",
            )
        elif (
            writer["password"] and writer["confirmed"] is True
        ):  # if the writer isn't confirmed he can register again.
            return render_template(
                "writers/register.html",
                status=f"You are already registered! Please login",
            )
        elif mongo.db.writers.find_one({"user_name": user_name}):
            return render_template(
                "writers/register.html",
                status=f"User name already taken! Please choose another one.",
            )

        mongo.db.writers.update_one(
            {
                "email": email,
                "accepted": True,
            },
            {
                "$set": {
                    "password": generate_password_hash(password),
                    "about": about,
                    "name": name,
                    "user_name": user_name,
                }
            },
        )

        file = request.files.get("file", None)
        if file:
            if upload_file(file=file, filename=user_name, current_app=current_app):
                pass
            else:
                return render_template(
                    "writers/register.html",
                    status=f"Error uploading file! Please try again.",
                )

        return redirect(url_for("auth.confirm", email=email, next="writers.register"))
    try:
        if session.get("confirmed")["confirmed"]:
            # ^ if there is a confirmed key in the session, and its value is True
            email = session.get("confirmed")["email"]
            mongo.db.writers.update_one(
                {"email": email, "confirmed": False},
                {
                    "$set": {
                        "confirmed": True,
                        "timezone": None,
                        "twitter": None,
                        "github": None,
                        "patreon": None,
                        "paypal": None,
                        "public_email": None,
                        "created_at": datetime.datetime.utcnow(),
                        "badges": ["writer"],
                        "website": None,
                        "views": 0,
                    }
                },
            )
            session["confirmed"] = {
                "email": email,
                "confirmed": False,
            }  # set confirmed back to False
            return render_template(
                "writers/register.html",
                status="You are now registered! You can login now",
            )
    except TypeError:
        pass
    # If method is GET
    return render_template("writers/register.html", status=None)


@bp.route("/create", methods=("POST", "GET"))
@login_required
def create():
    current_user.writer = mongo.db.writers.find_one({"_id": ObjectId(current_user.id)})

    if request.method == "POST":
        title = request.form["title"]
        if not title:
            return render_template(
                "writers/create.html", status=f"Please enter a title!"
            )

        description = request.form["description"]
        if not description:
            return render_template(
                "writers/create.html", status=f"Please enter a description!"
            )

        content = request.form["content"]
        if not content:
            return render_template(

gmt/templates/writers/apply.html
{% extends "layout.html" %}
{% block title %}Apply as writer{% endblock %}
{% block head %}
    <meta name="description"
          content="Apply to become a writer for Good Morning Tech. We are looking for writers who can write about technology, gadgets, and other related topics.">
    <meta name="twitter:description"
          content="Apply to become a writer for Good Morning Tech. We are looking for writers who can write about technology, gadgets, and other related topics.">
    <meta name="twitter:site"
          content="https://goodmorningtech.news/writers/apply">
    <meta name="twitter:creator" content="@goodmorningtech">
    <meta name="twitter:title" content="Writer: Application Page">
    <meta name="twitter:image"
          content="https://cdn.goodmorningtech.news/website/embed/Writer_Apply.png">
    <meta property="og:title" content="Writer: Application Page">
    <meta property="og:url"
          content="https://goodmorningtech.news/writers/apply">
    <meta property="og:image"
          content=" https://cdn.goodmorningtech.news/website/embed/Writer_Apply.png ">
    <meta name="author" content="Good Morning Tech">
    <meta name="title" content="Writer: Application Page">
{% endblock %}
{% block body %}
    <div class="flex justify-center items-center min-h-screen">
        <div class="w-full mx-10 md:mx-0 md:w-1/2 lg:w-1/3 divide-y-2 divide-black dark:divide-white">
            <div>
                <div class=" my-2 ">
                    <span class=" font-bold uppercase text-gray-500 tracking-wider font-gmt-karla ">Step: <span id="currentStep">1</span> of <span id="totalSteps">3</span></span>
                    <br>
                    <span class=" font-bold font-gmt-open-sans text-gray-800 dark:text-gmt-gray-secondary text-xl "
                          id="sectionName">Good Morning Tech Writer Application Form:</span>
                    <!--Progress Bar Div-->
                    <div id="progressBarParent"
                         class=" flex justify-center items-center my-2 ">
                        <div class=" w-full bg-gray-300 rounded-full ">
                            <div id="progressBar"
                                 class=" bg-gmt-red-primary text-xs w-1/3 leading-none text-center text-white rounded-full p-1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                {% if status %}
                    <div class="p-4 my-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-gray-800 dark:text-blue-400"
                         role="alert">
                        <p>{{ status }}</p>
                    </div>
                {% endif %}
                <form id="form"
                      method="POST"
                      enctype="multipart/form-data"
                      class="flex flex-col">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <div id="stepOne" class="min-h-full">
                        <div class="mb-4">
                            <label class="font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2">
                                Your Display Name (alias works too, can be changed later):
                            </label>
                            <input id="username"
                                   type="text"
                                   name="name"
                                   class="w-full p-2 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium"
                                   placeholder="John Doe"
                                   required>
                        </div>
                        <div class="mb-4">
                            <label class="font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2">
                                Your Email (please make sure you have subscribed to GMT with this email address):
                            </label>
                            <input id="userEmail"
                                   type="text"
                                   name="email"
                                   class="w-full p-2 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium"
                                   placeholder="johndoe@example.com"
                                   required>
                        </div>
                        <div class="mb-4">
                            <label class="font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2">
                                Alternate Point of Contact (Discord, other Email, Slack... etc.):
                            </label>
                            <input id="userContact"
                                   type="text"
                                   name="contact"
                                   class="w-full p-2 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium"
                                   placeholder="Discord: JohnDoe#1234, Email: JohnDoe, Slack: JohnDoesSlack">
                        </div>
                        <div class="flex justify-end my-2">
                            <span class="bg-blue-600 hover:bg-blue-700 shadow-lg text-white font-bold py-2 px-4 rounded-lg duration-100 ease-in-out transition-colors cursor-pointer w-32 h-12 flex justify-center items-center"
                                  id="nextBtnStepOne">
                                Proceed <i class="fas fa-angle-right"></i>
                            </span>
                        </div>
                    </div>                    
                    <div id="stepTwo" class="hidden min-h-full">
                        <div class=" font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2 mt-4 ">
                            Some general questions:
                        </div>
                        <label class="font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2 mt-4">
                            Why would you like to write for Good Morning Tech:
                            <textarea name="reasoning"
                                      id="whyWrite"
                                      cols="30"
                                      rows="4"
                                      class="w-full p-2 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium resize-none "
                                      placeholder="I would like to write because..."></textarea>
                        </label>
                        <label class=" font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2 mt-4 ">
                            What topics would you like to write about:
                            <textarea name="topics"
                                      id="topics"
                                      cols="30"
                                      rows="4"
                                      class="w-full p-2 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium resize-none "
                                      placeholder="I would like to write about..."></textarea>
                        </label>
                        <div class=" flex justify-end my-2 ">
                            <span class=" bg-blue-600 hover:bg-blue-700 shadow-lg text-white font-bold py-2 px-4 rounded-lg duration-100 ease-in-out transition-colors mx-4 w-32 h-12 cursor-pointer flex justify-center items-center "
                                  id="backBtnStepTwo">
                                <i class="fas fa-angle-left"></i> Go Back
                            </span>
                            <span class=" bg-blue-600 hover:bg-blue-700 shadow-lg text-white font-bold py-2 px-4 rounded-lg duration-100 ease-in-out transition-colors w-32 h-12 cursor-pointer flex justify-center items-center "
                                  id="nextBtnStepTwo">
                                Proceed <i class="fas fa-angle-right"></i>
                            </span>
                        </div>
                    </div>
                    <div id="stepThree" class="hidden">
                        <label class=" font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2 mt-4 ">
                            Please share a sample of your writing, this can be a link to a blog post, a Medium article,
                            or a Google Doc:
                            <textarea maxlength="400"
                                      class=" w-full p-2 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium resize-none "
                                      name="sample_link"
                                      placeholder="Sure! Here is a sample of my writing... Why Pigs Are The Best Animal In The World: ..., How To Make A Sandwich: ..."
                                      id="sample"
                                      cols="30"
                                      rows="4"
                                      required></textarea>
                        </label>
                        <label class=" font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2 mt-4 ">
                            We would love to see your writing style, please write a short article (200-500 words) on a
                            topic of your choice (avoid the usage of AI generated content) & keep this SFW:
                            <textarea maxlength="1200"
                                      class=" w-full p-2 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium resize-none "
                                      name="sample_article"
                                      placeholder="Sure! Here is a sample of my writing... Title: Why Pigs Are The Best Animal In The World Body: ..."
                                      id="article"
                                      cols="30"
                                      rows="8"
                                      required></textarea>
                        </label>
                        <label class=" font-bold text-gray-700 dark:text-gmt-gray-secondary block text-xl mb-2 mt-4 ">
                            Thank you for your interest in writing for Good Morning Tech, we will get back to you within
                            48 hours of your application submission through the email you provided (and/or your
                            alternate point of contact)!
                        </label>
                        <label>
                            <input id="terms"
                                   type="checkbox"
                                   name="terms"
                                   class=" w-4 h-4 rounded-lg shadow-sm focus:outline-none focus:shadow-outline text-gray-600 font-medium">
                            <span class=" text-gray-700 dark:text-gmt-gray-secondary font-gmt-open-sans font-semibold text-md md:text-lg ">
                                I agree to the <a href="{{ url_for("general.terms") }}" class=" text-blue-600 ">Terms of Service</a> and <a href="{{ url_for("general.privacy") }}" class=" text-blue-600 ">Privacy Policy</a> of Good Morning Tech.
                            </span>
                        </label>
                        <div class=" flex justify-end my-2 ">
                            <span class=" bg-blue-600 hover:bg-blue-700 shadow-lg text-white font-bold py-2 px-4 rounded-lg duration-100 ease-in-out transition-colors mx-4 w-32 h-12 cursor-pointer flex justify-center items-center "
                                  id="backBtnStepThree">
                                <i class="fas fa-angle-left"></i> Go Back
                            </span>
                            <button type="submit"
                                    disabled
                                    class=" bg-blue-600 hover:bg-blue-700 shadow-lg text-white font-bold py-2 px-4 rounded-lg duration-100 ease-in-out transition-colors w-44 h-12 disabled:opacity-50 disabled:cursor-not-allowed disabled:bg-slate-600 "
                                    id="submitFormBtn">
                                Submit Form <i class="fas fa-check"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <script src="{{ url_for('static', filename='JavaScript/writers/user-apply.js') }}"></script>
    </div>
{% endblock %}