gmt/views/writers.py
import datetime
import random

import re

import pytz
import requests
from bson import ObjectId
from flask import (
    Blueprint,
    current_app,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, current_user, login_required, logout_user

from .. import mongo, User
from ..utils import clean_html, upload_file, allowed_file_types

bp = Blueprint("writers", __name__, url_prefix="/writers")


@bp.route("/")
def writers():
    return redirect(url_for("writers.portal"))


@bp.route("/apply", methods=("POST", "GET"))
def apply():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    if request.method == "POST":
        email = request.form.get("email")
        reasoning = request.form.get("reasoning")
        alt_contact = request.form.get("alt_contact")
        name = request.form.get("name")
        topics = request.form.get("topics")
        sample_link = request.form.get("sample_link")
        sample_article = request.form.get("sample_article")
        if not email or not reasoning or not name:
            return render_template(
                "writers/apply.html",
                status=f"Please fill in all fields!",
                current_user=current_user,
                no_meta=True,
            )

        user = mongo.db.users.find_one({"email": email, "confirmed": True})
        if not user:
            return render_template(
                "writers/apply.html",
                status=f"Please subscribe first,"
                f" or confirm your email by registering subscribing.",
                current_user=current_user,
                no_meta=True,
            )
        elif mongo.db.writers.find_one({"email": email, "accepted": True}):
            return render_template(
                "writers/apply.html",
                status=f"You are already a writer!",
                current_user=current_user,
                no_meta=True,
            )
        elif mongo.db.writers.find_one({"email": email, "accepted": False}):
            return render_template(
                "writers/apply.html",
                status=f"You have already applied!",
                current_user=current_user,
                no_meta=True,
            )

        writer = {
            "email": email,
            "name": name,
            "reasoning": reasoning,
            "accepted": False,
            "password": None,
            "user_name": None,  # NEEDS TO BE UNIQUE
            "confirmed": False,  # needs to confirm email when registering as writer
            "alt_contact": alt_contact,
            "topics": topics,
            "sample_link": sample_link,
            "sample_article": sample_article,
            "register_date": datetime.datetime.utcnow(),
        }
        mongo.db.writers.insert_one(writer)

        if current_app.config["WRITER_WEBHOOK"] is None:
            print("No webhook set, please set WRITER_WEBHOOK")

        # POSTS the information to a discord channel using a webhook, so we can either accept it or not
        requests.post(
            current_app.config["WRITER_WEBHOOK"],
            json={
                "content": f"""
                User with email {email} requested to join as writer. Reasoning: {reasoning}\nTopics: {topics}\nSample article link: {sample_link}\nSample article: {sample_article}\nalt contact: {alt_contact}
                """
            },
        )
        return render_template(
            "writers/apply.html",
            status=f"Thank you for applying! We will get back to you as soon as possible.",
            current_user=current_user,
            no_meta=True,
        )

    return render_template("writers/apply.html", status=None, no_meta=True)


@bp.route("/login", methods=("POST", "GET"))
def login():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        writer_db = mongo.db.writers.find_one({"email": email, "accepted": True})

        if not writer_db:
            return render_template(
                "writers/login.html",
                status=f"You are not a writer!",
                current_user=current_user,
            )
        elif not check_password_hash(writer_db["password"], password):
            return render_template("writers/login.html", status=f"Wrong password!")
        elif writer_db["confirmed"] is False:
            return render_template(
                "writers/login.html",
                status=f"Please confirm your email first!",
                current_user=current_user,
            )

        user = User()
        user.id = writer_db["_id"]

        login_user(user, remember=True)

        return redirect(url_for("writers.portal"))
    return render_template("writers/login.html", status=None)


@bp.route("/logout", methods=["POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("general.index"))


@bp.route("/register", methods=("POST", "GET"))
def register():
    if current_user.is_authenticated:
        current_user.writer = mongo.db.writers.find_one(
            {"_id": ObjectId(current_user.id)}
        )
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        password_confirm = request.form["password_confirm"]
        about = request.form.get("about")
        name = request.form.get("name")
        user_name = request.form.get("user_name")

        if len(user_name) < 3 or re.fullmatch("^[\w.-]+$", user_name) is None:
            return render_template(
                "writers/apply.html",
                status=f"User name must be at least 3 characters long and only contain"
                f" alphanumeric characters, underscores, dashes and dots.",
            )

        if password != password_confirm:
            return render_template(
                "writers/register.html", status=f"Passwords dont match!"
            )

        writer = mongo.db.writers.find_one({"email": email, "accepted": True})
        if not writer:
            return render_template(
                "writers/register.html",
                status=f"You are not a writer! Please apply first or get accepted.",
            )
        elif (
            writer["password"] and writer["confirmed"] is True
        ):  # if the writer isn't confirmed he can register again.
            return render_template(
                "writers/register.html",
                status=f"You are already registered! Please login",
            )
        elif mongo.db.writers.find_one({"user_name": user_name}):
            return render_template(
                "writers/register.html",
                status=f"User name already taken! Please choose another one.",
            )

        mongo.db.writers.update_one(
            {
                "email": email,
                "accepted": True,
            },
            {
                "$set": {
                    "password": generate_password_hash(password),
                    "about": about,
                    "name": name,
                    "user_name": user_name,
                }
            },
        )

        file = request.files.get("file", None)
        if file:
            if upload_file(file=file, filename=user_name, current_app=current_app):
                pass
            else:
                return render_template(
                    "writers/register.html",
                    status=f"Error uploading file! Please try again.",
                )

        return redirect(url_for("auth.confirm", email=email, next="writers.register"))
    try:
        if session.get("confirmed")["confirmed"]:
            # ^ if there is a confirmed key in the session, and its value is True
            email = session.get("confirmed")["email"]
            mongo.db.writers.update_one(
                {"email": email, "confirmed": False},
                {
                    "$set": {
                        "confirmed": True,
                        "timezone": None,
                        "twitter": None,
                        "github": None,
                        "patreon": None,
                        "paypal": None,
                        "public_email": None,
                        "created_at": datetime.datetime.utcnow(),
                        "badges": ["writer"],
                        "website": None,
                        "views": 0,
                    }
                },
            )
            session["confirmed"] = {
                "email": email,
                "confirmed": False,
            }  # set confirmed back to False
            return render_template(
                "writers/register.html",
                status="You are now registered! You can login now",
            )
    except TypeError:
        pass
    # If method is GET
    return render_template("writers/register.html", status=None)


@bp.route("/create", methods=("POST", "GET"))
@login_required
def create():
    current_user.writer = mongo.db.writers.find_one({"_id": ObjectId(current_user.id)})

    if request.method == "POST":
        title = request.form["title"]
        if not title:
            return render_template(
                "writers/create.html", status=f"Please enter a title!"
            )

        description = request.form["description"]
        if not description:
            return render_template(
                "writers/create.html", status=f"Please enter a description!"
            )

        content = request.form["content"]
        if not content:
            return render_template(

gmt/templates/apply.html
{% extends "layout.html" %}
{% block title %}Apply as writer{% endblock %}
{% block body %}
    <h1>Apply as writer</h1>
    <p>Apply as writer, need to have an existing subscription to apply.</p>
    {% if status %}
        <div class="p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-gray-800 dark:text-blue-400"
             role="alert">
            <p>{{ status }}</p>
        </div>
    {% endif %}
    <form method="POST">
        <label>
            Your email address(needs to be registered to the newsletter):
            <input name="email" type="email">
        </label>
        <br>
        <label>
            Your name:
            <input name="name" type="text">
        </label>
        <br>
        <label>
            Reason why you want to join:
            <input name="reasoning" type="text">
        </label>
        <input type="submit">
    </form>
{% endblock %}

gmt/templates/confirm.html
{% extends  "layout.html" %}
{% block title %}Confirm Email{% endblock %}
{%  block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='CSS/confirm.css') }}">
{% endblock %}
{% block body %}

<form method="POST">
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif %}
    {% if status == "sent" %}
    <main>
        <div class="text">We have emailed you at <span class="email">{{ email }}</span> with a verification link, once you click that, you'll be able to access our newsletter.</div>
        <div class="image"><img src="{{ url_for('static', filename = 'Images/mailbox.svg') }}" alt=""></div>
        <div class="email-fail">Did not recieve an email? Click <a class="resend" href="">here</a> or check your spam folder.</div>
    </main>
    {% elif status == "received" %}
    <main>
        <div class="container">
            <div><h1>Confirm your email by clicking the button below.</h1></div>
            <div><button type="submit" class="confirmed">Confirm Email</button></div>
        </div>
    </main>

    {% endif %}
</form>
{% endblock %}

gmt/templates/leave.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ciao | Good Morning Tech</title>
    <link rel="stylesheet" href="{{ url_for('static', filename = 'CSS/leave.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <meta property="og:title" content="Unsubscribe from Good Morning Tech">
    <meta property="og:locale" content="en_US">
    <meta property="og:url" content="https://github.com/organizations/GoodMorninTech">
    <meta property="og:description" content="Although we don't wish to see you leave, some things are beyound our control. Unsubscribe from Good Morning Tech's newsletter.">
    <meta property="og:site_name" content="Good Morning Tech">
    <meta property="og:image" content="https://goodmorningtech.news/static/goodbye.png">
    <meta name="twitter:title" content="Unsubscribe from Good Morning Tech">
    <meta name="twitter:description" content="Although we don't wish to see you leave, some things are beyound our control. Unsubscribe from Good Morning Tech's newsletter.">
    <meta name="twitter:image" content="https://goodmorningtech.news/static/goodbye.png">
    <meta name="twitter:card" content="summary_large_image">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <main>
        <div>
            <h1>We're <u>sad</u> to see you leave...</h1>
        </div>
        <div>
            <img src="{{ url_for('static', filename = 'Images/goodbye.svg') }}" alt="goodbye">
        </div>
        <div>
            <h2>To unsubscribe, enter your email and we'll shoot you an email with details to help you opt-out.</h2>
        </div>
        {% if error %}
            <p class="error">{{ error }}</p>
        {% endif %}
        <div>
            <form class="form-div" method="POST">
                <div>
                    <input class="email" required type="email" placeholder="justinfoley@goodmorning.tech" name="email">
                </div>
                <div>
                    <button class="submit-btn" type="submit">Send Email</button>
                </div>
            </form>
        </div>
        <div>
            <h3>In case you ever change your mind, you can always <a href="{{ url_for('auth.register') }}">resubscribe</a>.</h3>
        </div>
    </main>
</body>
</html>

gmt/templates/signup.html
{% extends "layout.html" %}
{% block title %}Sign up{% endblock title %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename = 'CSS/sign-up.css') }}">
{% endblock head %}
{% block body %}
<main>
    <div class="container">
        <div class="thumbnail">
            <div class="title">Welcome to <br>Good Morning Tech</div>
            <!--Alternate video: https://assets7.lottiefiles.com/packages/lf20_mhdn5srg.json-->
            <lottie-player src="https://assets6.lottiefiles.com/private_files/lf30_iywakhjv.json"
                background="transparent" speed="1" style="width: 300px; height: 300px;" loop autoplay></lottie-player>
            <!-- <img src="{{ url_for('static', filename = 'Images/dude_slurping.svg') }}"> -->
        </div>
        <div class="form">
            <form method="post">
                <div>
                    <h1 class="form-title">Join our newsletter</h1>
                </div>
                {% if error %}
                <p class="error">{{ error }}</p>
                <!-- error class needs styling -->
                {% endif %}

                <div><input name="email" type="email" class="email-box email-address" placeholder="Email address"
                        required></div>
                <div class="time-box">
                    <select name="timezone-selection" required class="timezone">
                        <!-- value needs to be UTC time offset -->
                        <option value="placeholder" disabled selected hidden>Timezone</option>
                        <option class="PST" value="-8">Pacific Time (UTC -8)</option>
                        <option class="MST" value="-7">Mountain Time (UTC -7)</option>
                        <option class="CST" value="-6">Central Time (UTC -6)</option>
                        <option class="EST" value="-5">Eastern Time (UTC -5)</option>
                        <option class="BRT" value="-3">Brasilia Standard Time (UTC -3)</option>
                        <option class="GMT UTC" value="0">Greenwich Mean Time (UTC +0)</option>
                        <option class="CET" value="1">Central European Time (UTC +1)</option>
                        <option class="MSK" value="3">Moscow Standard Time (UTC +3)</option>
                        <option class="GET" value="4">Georgian Standard Time (UTC +4)</option>
                        <option class="IST" value="5.30">Indian Standard Time (UTC +5:30)</option>
                        <option class="CST" value="8">China Standard Time (UTC +8)</option>
                        <option class="JST" value="9">Japan Standard Time (UTC +9)</option>
                        <option class="AEDT" value="10">Australian Eastern Standard Time (UTC +11)</option>
                    </select>
                    <select name="time-selection" required class="time-selection">
                        <option value="" disabled selected hidden>Time</option>
                        <option value="00">00:00</option>
                        <option value="01">01:00</option>
                        <option value="02">02:00</option>
                        <option value="03">03:00</option>
                        <option value="04">04:00</option>
                        <option value="05">05:00</option>
                        <option value="06">06:00</option>
                        <option value="07">07:00</option>
                        <option value="08">08:00</option>
                        <option value="09">09:00</option>
                        <option value="10">10:00</option>
                        <option value="11">11:00</option>
                        <option value="12">12:00</option>
                        <option value="13">13:00</option>
                        <option value="14">14:00</option>
                        <option value="15">15:00</option>
                        <option value="16">16:00</option>
                        <option value="17">17:00</option>
                        <option value="18">18:00</option>
                        <option value="19">19:00</option>
                        <option value="20">20:00</option>
                        <option value="21">21:00</option>
                        <option value="22">22:00</option>
                        <option value="23">23:00</option>
                    </select>
                </div>
                <div class="day-selection">
                    <label for="days" class="days-label">Days you'd like the mail on</label>
                    <div class="days-input">
                        <div class="everyday"><input type="checkbox" class="everyday checkbox" name="days" checked>
                            Everyday
                        </div>
                        <div class="weekday"><input type="checkbox" class="weekdays checkbox" name="days"> Weekdays
                        </div>
                        <div class="weekend"><input type="checkbox" class="weekends checkbox" name="days"> Weekends
                        </div>
                    </div>
                </div>
                <div class="article-counter-container">
                    <label for="article-counter">How many articles would you like?</label>
                    <input type="range" max="12" min="4" value="6" name="article-counter" class="slider">
                    <p class="label-for-range slider-counter">Count: 6</p>
                </div>
                <div class="tos">By subscribing you agree to our <a href="#">terms of service</a>.</div>
                <div class="submit-box">
                    <button type="submit" class="submit">Subscribe!</button>
                </div>
            </form>
        </div>
    </div>
</main>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<script src="{{ url_for('static', filename = 'JavaScript/sign-up.js') }}"></script>
{% endblock body %}

gmt/templates/writer_login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block body %}
    <h1>Login</h1>
    {% if status %}
        <div class="p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-gray-800 dark:text-blue-400"
             role="alert">
            <p>{{ status }}</p>
        </div>
    {% endif %}
    <form method="POST">
        <label>
            Your Email:
            <input name="email" type="email">
        </label>
        <br>
        <label>
            Your Password:
            <input name="password" type="password">
        </label>
        <br>
        <input type="submit">
    </form>
    <p class="text-blue-600">
        If you haven't applied: <a href="{{ url_for('writers.apply') }}">Apply Here</a>
    </p>
    <p class="text-blue-600">
        If you got accepted and don't have an account: <a href="{{ url_for('writers.register') }}">Register Here</a>
    </p>
{% endblock %}

gmt/templates/writer_register.html
{% extends "layout.html" %}
{% block title %}Register{% endblock %}
{% block body %}
    <h1>Register</h1>
    {% if status %}
        <div class="p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-gray-800 dark:text-blue-400"
             role="alert">
            <p>{{ status }}</p>
        </div>
    {% endif %}
    <form method="POST">
        <label>
            Your Email:
            <input name="email" type="email">
        </label>
        <br>
        <label>
            Your Password:
            <input name="password" type="password">
        </label>
        <br>
        <label>
            Confirm Password:
            <input name="password_confirm" type="password">
        </label>
        <br>
        <input type="submit">
    </form>
    <p class="text-blue-600">
        If you haven't applied: <a href="{{ url_for('writers.apply') }}">Apply Here</a>
    </p>
    <p class="text-blue-600">
        If you registered already: <a href="{{ url_for('writers.login') }}">Login Here</a>
    </p>
{% endblock %}